apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yml
  - services.yml
  - configMap.yml
  - secret.yml

labels:
  - pairs:
      app: my-app

configurations:
  - name: current-context
    namespace: default

transformers:
  - name: set-context
    type: patch
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: GOOGLE_CLOUD_PROJECT
            value: [PROJECT_ID]
          - name: GOOGLE_CLOUD_REGION
            value: [ZONE]
          - name: GOOGLE_CLOUD_CLUSTER
            value: [CLUSTER_NAME]
      - op: add
        path: /spec/template/spec/containers/0/command
        value:
          - /bin/sh
          - -c
          - |
            gcloud container clusters get-credentials [CLUSTER_NAME] --zone [ZONE] --project [PROJECT_ID] &&
            exec /usr/local/bin/your-app-executable
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: gcr.io/[PROJECT_ID]/your-app-image:latest
      - op: add
        path: /spec/template/spec/containers/0/command
        value:
          - /bin/sh
          - -c
          - |
            kubectl get nodes
            exec /usr/local/bin/your-app-executable